# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

PreCommit:
#  RuboCop:
#     enabled: true
#     on_warn: fail # Treat all warnings as failures
#     description: 'Analyze with RuboCop'
#     required_executable: 'rubocop'
#     flags: ['--format=emacs', '--force-exclusion', '--display-cop-names']
#     install_command: 'gem install rubocop'
#     include:
#       - '**/*.gemspec'
#       - '**/*.rake'
#       - '**/*.rb'
#       - '**/*.ru'
#       - '**/Gemfile'
#       - '**/Rakefile'
  RailsBestPractices:
      enabled: false
#     description: 'Checking Rails best practices'
  BundleAudit:
      enabled: true
#     description: 'Check for vulnerable versions of gems'
#     required_executable: 'bundle-audit'
#     install_command: 'gem install bundler-audit'
#  Reek:
#      enabled: true
#     description: 'Analyze with Reek'
#     required_executable: 'reek'
#     flags: ['--single-line', '--no-color']
#     install_command: 'gem install reek'
#     include:
#       - '**/*.gemspec'
#       - '**/*.rake'
#       - '**/*.rb'
#       - '**/Gemfile'
#       - '**/Rakefile'

PrePush:
  Brakeman:
    enabled: false
#   description: 'Check for security vulnerabilities'
#   required_executable: 'brakeman'
#   flags: ['--exit-on-warn', '--quiet', '--summary']
#   install_command: 'gem install brakeman'

#  TrailingWhitespace:
#    enabled: true
#    exclude:
#      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
#
#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  IndexTags:
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes
