# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17c86af14207069960feb8992473ac1da771e1d1a5d7a6ba6bace382ebd84ef216ae9df6fcd072b30fe7469c294235738d89f3e54da0bac48d04d04866091cf7

test:
  secret_key_base: 12256aad5ebe2fd445c228d158f019586f3a616c9f59fa632be17daf48f7461745749b2fe02c5eeaea2288e3764629d297703d2c63050d757026d0e4783c0b20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
