production:
  pid_file: /home/deploy/mob/shared/tmp/searchd.pid
  indices_location: /home/deploy/mob/shared/db/sphinx
  configuration_file: /home/deploy/mob/shared/production.sphinx.conf
  binlog_path: /home/deploy/mob/shared/binlog
